# Generated by Django 5.1 on 2024-12-06 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Order ID')),
                ('check_in', models.DateField(blank=True, null=True, verbose_name='Check-in Date')),
                ('check_out', models.DateField(blank=True, null=True, verbose_name='Check-out Date')),
                ('nights', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('type_booking', models.CharField(db_index=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core_payments.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='OrderPlacementStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('annoynmous_track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_control.anonymousbooking')),
                ('orders', models.ManyToManyField(related_name='storages', to='core_payments.order', verbose_name='Orders')),
            ],
            options={
                'verbose_name': 'Order Placement Storage',
                'verbose_name_plural': 'Order Placement Storages',
            },
        ),
        migrations.CreateModel(
            name='PaymentUserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone_no', models.CharField(db_index=True, default='', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Not Confirmed', 'Not Confirmed')], db_index=True, default='', max_length=100)),
                ('contury', models.CharField(db_index=True, default='', max_length=100)),
                ('state', models.CharField(db_index=True, default='', max_length=100)),
                ('date', models.DateField(db_index=True, default='2000-01-01')),
                ('city', models.CharField(db_index=True, default='', max_length=100)),
                ('address', models.TextField(db_index=True)),
                ('address_no_2', models.TextField(db_index=True, default='', null=True)),
                ('annoynmous_tracer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_control.anonymousbooking')),
            ],
        ),
    ]
