# Generated by Django 5.1 on 2024-12-10 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentuserdetail',
            name='order_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
