# Generated by Django 5.1 on 2024-12-11 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_control', '0001_initial'),
        ('core_payments', '0002_paymentuserdetail_order_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplacementstorage',
            name='annoynmous_track',
        ),
        migrations.AddField(
            model_name='orderplacementstorage',
            name='anonymous_track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_control.anonymousbooking', verbose_name='Anonymous Booking'),
        ),
        migrations.AlterField(
            model_name='order',
            name='nights',
            field=models.PositiveIntegerField(default=0, verbose_name='Nights'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_booking',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Booking Type'),
        ),
    ]
