# Generated by Django 5.1 on 2024-12-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_payments', '0003_remove_orderplacementstorage_annoynmous_track_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplacementstorage',
            name='orders',
        ),
        migrations.AddField(
            model_name='orderplacementstorage',
            name='orders_items',
            field=models.ManyToManyField(related_name='storages', to='core_payments.orderitem', verbose_name='Orders'),
        ),
    ]
