# Generated by Django 5.1 on 2024-12-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_payments', '0004_remove_orderplacementstorage_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pub_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Order ID'),
        ),
    ]
