# Generated by Django 5.1 on 2024-12-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_payments', '0005_order_pub_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentuserdetail',
            name='time_zone',
            field=models.CharField(blank=True, db_index=True, default='UTC', max_length=50, null=True),
        ),
    ]
