# Generated by Django 5.1 on 2024-12-01 06:21

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ImaraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.TextField(db_index=True, default='', help_text='The physical address of the organization.', verbose_name='Street Address')),
                ('phone_number', models.CharField(db_index=True, default='', help_text='Contact phone number.', max_length=30, verbose_name='Phone Number')),
                ('email', models.EmailField(db_index=True, default='', help_text='Contact email address.', max_length=254, verbose_name='Email Address')),
                ('facebook_link', models.URLField(blank=True, help_text="URL to the organization's Facebook page.", null=True, verbose_name='Facebook Page Link')),
                ('instagram_link', models.URLField(blank=True, help_text="URL to the organization's Instagram profile.", null=True, verbose_name='Instagram Profile Link')),
                ('twitter_link', models.URLField(blank=True, help_text="URL to the organization's Twitter profile.", null=True, verbose_name='Twitter Profile Link')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated.', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Imara Information',
                'verbose_name_plural': 'Imara Information',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('_id', models.CharField(db_index=True, default='', max_length=100, null=True, unique=True)),
                ('profile_url', models.ImageField(blank=True, db_index=True, null=True, upload_to='profile/images')),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('username', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('date_of_bith', models.DateField(db_index=True, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone_no', models.CharField(db_index=True, max_length=20, null=True)),
                ('city', models.CharField(db_index=True, max_length=100, null=True)),
                ('nationality', models.CharField(db_index=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], db_index=True, max_length=100, null=True)),
                ('address', models.TextField(db_index=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_login', models.DateTimeField(db_index=True, default=None, null=True)),
                ('is_blocked', models.BooleanField(db_index=True, default=False, null=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('is_staff', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('password', models.CharField(db_index=True, default=None, max_length=200)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_permissions', to='auth.permission')),
                ('users_messaging_container', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
