# Generated by Django 5.1 on 2024-12-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
