# Generated by Django 5.1 on 2024-12-11 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0002_tables_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedroom',
            name='availability_from',
            field=models.DateField(default=None, null=True, verbose_name='Availability From'),
        ),
        migrations.AlterField(
            model_name='bedroom',
            name='availability_till',
            field=models.DateField(default=None, null=True, verbose_name='Availability Till'),
        ),
        migrations.AlterField(
            model_name='bedroom',
            name='available_days',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Available Days'),
        ),
        migrations.AlterField(
            model_name='bedroom',
            name='capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='bedroom',
            name='description',
            field=models.TextField(db_index=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='bedroom',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_posts.hotel', verbose_name='Hotel'),
        ),
        migrations.AlterField(
            model_name='bedroom',
            name='image',
            field=models.ImageField(db_index=True, null=True, upload_to='beds/images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='bedroom',
            name='is_booked',
            field=models.BooleanField(default=False, verbose_name='Is Booked'),
        ),
        migrations.AlterField(
            model_name='bedroom',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='bedroom',
            name='reviews',
            field=models.ManyToManyField(blank=True, db_index=True, to='core_posts.review', verbose_name='Reviews'),
        ),
        migrations.AlterField(
            model_name='bedroom',
            name='room_amenities',
            field=models.ManyToManyField(db_index=True, related_name='bed_rooms', to='core_posts.amenities', verbose_name='Room Amenities'),
        ),
        migrations.AlterField(
            model_name='bedroom',
            name='room_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Room ID'),
        ),
        migrations.AlterField(
            model_name='bedroom',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite')], db_index=True, max_length=100, verbose_name='Room Type'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='availability_from',
            field=models.DateField(default=None, null=True, verbose_name='Availability From'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='availability_till',
            field=models.DateField(default=None, null=True, verbose_name='Availability Till'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='available_days',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Available Days'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='images',
            field=models.ImageField(db_index=True, null=True, upload_to='table/images', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='is_booked',
            field=models.BooleanField(default=False, verbose_name='Is Booked'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_posts.restaurant', verbose_name='Restaurant'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='review',
            field=models.ManyToManyField(blank=True, db_index=True, to='core_posts.review', verbose_name='Reviews'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='table_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Table ID'),
        ),
    ]
