# Generated by Django 5.1 on 2024-12-14 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_control', '0001_initial'),
        ('core_posts', '0003_alter_bedroom_availability_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouritelist',
            name='name',
        ),
        migrations.AddField(
            model_name='favouritelist',
            name='unknown_track',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='core_control.anonymousbooking'),
        ),
        migrations.AlterField(
            model_name='favouritelist',
            name='user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
